# Generated by Django 5.0.6 on 2024-06-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
