# Generated by Django 5.0.6 on 2024-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_fetcher', '0002_alter_token_last_updated_alter_token_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
